apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/aggie-experts/pub/webapp:5.2.7
      nodeSelector:
        intended-for: ae-dev-frontend
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: webapp-api
              topologyKey: kubernetes.io/hostname
