apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: database
          image: us-west1-docker.pkg.dev/aggie-experts/pub/ae-postgres:anduin
      nodeSelector:
        intended-for: ae-dev-harvest
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
