apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: database
          image: us-west1-docker.pkg.dev/aggie-experts/pub/ae-postgres:anduin
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
