services:

  elasticsearch:
    image: ${IMAGE_FIN_FIN_ELASTIC_SEARCH}
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: unless-stopped

networks:
  default:
    name: aggie_experts_prod

volumes:
  es-data:
    driver: local