services:
  harvest:
    image: ${IMAGE_AGGIE_EXPERTS_HARVEST}
    env_file:
      - .env
    environment:
      - EXPERTS_CACHE_ROOT_DIR=/opt/cache
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - DAGSTER_POSTGRES_USER=postgres
      - DAGSTER_POSTGRES_PASSWORD=postgres
      - DAGSTER_POSTGRES_DB=dagster
      - DAGSTER_CURRENT_IMAGE=${IMAGE_AGGIE_EXPERTS_HARVEST}
    volumes:
      - ../../../aggie-experts/harvest/lib:/opt/harvest/lib
      - ../../../aggie-experts/harvest/bin:/opt/harvest/bin
      - ../../../aggie-experts/harvest/vocabularies:/opt/harvest/vocabularies
      - ../../../aggie-experts/dagster/defs.py:/opt/harvest/defs.py
      - ../../../aggie-experts/service-account.json:/service-account.json
    ports:
      - "3000:3000"
    command: ["dagster", "dev",  "-h", "0.0.0.0", "-p", "3000", "-f", "/opt/harvest/defs.py"]

  postgres:
    image: ${IMAGE_PROJECT_ANDUIN_ANDUIN_PG}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  superset:
    image: ${IMAGE_PROJECT_ANDUIN_SUPERSET}
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
      - SUPERSET_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/superset
      - USE_KEYCLOAK=true
      - KEYCLOAK_REALM_NAME=aggie-experts
      - KEYCLOAK_CLIENT_ID=anduin
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ROLE_DOT_PATH=resource_access.anduin.roles
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
      - superset_init:/etc/superset/init
    # command: ["bash", "-c", "/app/docker/superset-start.sh"]

networks:
  aggie_experts_prod:
    external: true

volumes:
  data_cache:
    driver: local
  dagster_home:
    driver: local
  pg_data:
    driver: local
  superset_home:
    driver: local
  superset_init:
    driver: local