services:

  auth-gateway:
    image: ${IMAGE_PROJECT_ANDUIN_AUTH_GATEWAY}
    env_file: 
      - .env
    environment:
      - PORT=4000
      - APP_NAME=Aggie Experts - Harvest
      - POSTGRES_PASSWORD=postgres
      - CASK_URL=http://caskfs-ui:3000
      - DAGSTER_URL=http://dagster-ui:3000
      - PROXY_ADDITIONAL_SERVICE_LINKS={"name":"webapp","title":"Webapp","subtitle":"Aggie Experts","link":"http://localhost:3000","color":"brand-secondary-70","icon":"fas fa-browser"}
    volumes:
      - ../../../../project-anduin/auth-gateway/controllers:/app/controllers
      - ../../../../project-anduin/auth-gateway/lib:/app/lib
      - ../../../../project-anduin/auth-gateway/client:/app/client
      - ../../../../project-anduin/auth-gateway/index.js:/app/index.js
    ports:
      - "4000:4000"

  dagster-ui:
    image: ${IMAGE_AGGIE_EXPERTS_HARVEST}
    env_file:
      - .env
    environment:
      - DAGSTER_POSTGRES_USER=postgres
      - DAGSTER_POSTGRES_PASSWORD=postgres
      - DAGSTER_POSTGRES_DB=dagster
      - DAGSTER_CURRENT_IMAGE=${IMAGE_AGGIE_EXPERTS_HARVEST}
    volumes:
      - dagster_storage:/opt/dagster/dagster_home/storage
      - ../../../aggie-experts/dagster/defs.py:/opt/harvest/defs.py
    depends_on:
      - postgres
    command: ["dagster-webserver", "--path-prefix", "/dagster", "-h", "0.0.0.0", "-p", "3000", "-f", "/opt/harvest/defs.py"]

  dagster-daemon:
    image: ${IMAGE_AGGIE_EXPERTS_HARVEST}
    env_file:
      - .env
    environment:
      - EXPERTS_CACHE_ROOT_DIR=/opt/cache
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - CASKFS_PG_HOST=postgres
      - CASKFS_ENABLE_POWERWASH=true
      - CASKFS_ROOT_DIR=/opt/cache
      - CASKFS_ACL_ENABLED=false
      - CASKFS_WEBAPP_PORT=3001
      - CASKFS_WEBAPP_ENV=dev
      - DAGSTER_POSTGRES_USER=postgres
      - DAGSTER_POSTGRES_PASSWORD=postgres
      - DAGSTER_POSTGRES_DB=dagster
      - DAGSTER_CURRENT_IMAGE=${IMAGE_AGGIE_EXPERTS_HARVEST}
    volumes:
      # dagster
      - dagster_storage:/opt/dagster/dagster_home/storage
      # caskfs code
      - ../../../caskfs/src:/opt/caskfs/src
      # ae harvest code
      - ../../../aggie-experts/harvest/lib:/opt/harvest/lib
      - ../../../aggie-experts/harvest/bin:/opt/harvest/bin
      - ../../../aggie-experts/harvest/vocabularies:/opt/harvest/vocabularies
      - ../../../aggie-experts/dagster/defs.py:/opt/harvest/defs.py
      - ../../../aggie-experts/service-account.json:/service-account.json
      - data_cache:/opt/cache
    depends_on:
      - postgres
    command: ["dagster-daemon", "run", "-f", "/opt/harvest/defs.py"]

  caskfs-ui:
    image: ${IMAGE_AGGIE_EXPERTS_HARVEST}
    env_file:
      - .env
    environment:
      - EXPERTS_CACHE_ROOT_DIR=/opt/cache
      - CASKFS_PG_HOST=postgres
      - CASKFS_ENABLE_POWERWASH=true
      - CASKFS_ROOT_DIR=/opt/cache
      - CASKFS_ACL_ENABLED=false
      - CASKFS_WEBAPP_ENV=dev
      - CASKFS_WEBAPP_PATH_PREFIX=/cask
    volumes:
      # caskfs code
      - ../../../caskfs/src:/opt/caskfs/src
      - data_cache:/opt/cache
    depends_on:
      - postgres
    command: ["cask", "serve"]

  postgres:
    image: ${IMAGE_PROJECT_ANDUIN_ANDUIN_PG}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  superset:
    image: ${IMAGE_PROJECT_ANDUIN_SUPERSET}
    env_file:
      - .env
    environment:
      - DASHBOARD_FILE=gs://anduin-dashboards/dashboard_year_week_update.zip
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - SUPERSET_APP_ROOT=/superset
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
      - superset_init:/etc/superset/init
      - ../../../aggie-experts/service-account.json:/service-account.json
    # command: ["bash", "-c", "/app/docker/superset-start.sh"]
    # command: ["bash", "-c", "tail -f /dev/null"]

networks:
  default:
    name: aggie_experts_prod

volumes:
  data_cache:
    driver: local
  dagster_storage:
    driver: local
  pg_data:
    driver: local
  superset_home:
    driver: local
  superset_init:
    driver: local