services:
  harvest:
    image: ${IMAGE_AGGIE_EXPERTS_HARVEST}
    env_file:
      - .env
    environment:
      - EXPERTS_CACHE_ROOT_DIR=/opt/cache
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - CASKFS_PG_HOST=postgres
      - CASKFS_ENABLE_POWERWASH=true
      - CASKFS_ROOT_DIR=/opt/cache
      - CASKFS_ACL_ENABLED=false
      - CASKFS_WEBAPP_PORT=3001
      - CASKFS_WEBAPP_ENV=dev
      - DAGSTER_POSTGRES_USER=postgres
      - DAGSTER_POSTGRES_PASSWORD=postgres
      - DAGSTER_POSTGRES_DB=dagster
      - DAGSTER_CURRENT_IMAGE=${IMAGE_AGGIE_EXPERTS_HARVEST}
    volumes:
      # caskfs code
      - ../../../caskfs/src:/opt/caskfs/src
      # harvest code
      - ../../../aggie-experts/harvest/lib:/opt/harvest/lib
      - ../../../aggie-experts/harvest/bin:/opt/harvest/bin
      - ../../../aggie-experts/harvest/vocabularies:/opt/harvest/vocabularies
      - ../../../aggie-experts/dagster/defs.py:/opt/harvest/defs.py
      - ../../../aggie-experts/service-account.json:/service-account.json
      - data_cache:/opt/cache
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: ["dagster", "dev",  "-h", "0.0.0.0", "-p", "3000", "-f", "/opt/harvest/defs.py"]

  caskfs-ui:
    image: ${IMAGE_AGGIE_EXPERTS_HARVEST}
    env_file:
      - .env
    environment:
      - EXPERTS_CACHE_ROOT_DIR=/opt/cache
      - CASKFS_PG_HOST=postgres
      - CASKFS_ENABLE_POWERWASH=true
      - CASKFS_ROOT_DIR=/opt/cache
      - CASKFS_ACL_ENABLED=false
      - CASKFS_WEBAPP_PORT=3001
      - CASKFS_WEBAPP_ENV=dev
    volumes:
      # caskfs code
      - ../../../caskfs/src:/opt/caskfs/src
      - data_cache:/opt/cache
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    command: ["cask", "serve"]

  postgres:
    image: ${IMAGE_PROJECT_ANDUIN_ANDUIN_PG}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  superset:
    image: ${IMAGE_PROJECT_ANDUIN_SUPERSET}
    env_file:
      - .env
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - DASHBOARD_FILE=gs://anduin-dashboards/dashboard_year_week_update.zip
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - USE_KEYCLOAK=true
      - KEYCLOAK_REALM_NAME=aggie-experts
      - KEYCLOAK_CLIENT_ID=anduin
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_ROLE_DOT_PATH=resource_access.anduin.roles
      - TALISMAN_ENABLED=false
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
      - superset_init:/etc/superset/init
      - ../../../aggie-experts/service-account.json:/service-account.json
    # command: ["bash", "-c", "/app/docker/superset-start.sh"]

networks:
  default:
    name: aggie_experts_prod

volumes:
  data_cache:
    driver: local
  dagster_home:
    driver: local
  pg_data:
    driver: local
  superset_home:
    driver: local
  superset_init:
    driver: local