apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: superset
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/digital-ucdavis-edu/pub/superset:main
  volumeClaimTemplates:
    - metadata:
        name: superset-home
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: superset-init
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
