apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: service
        image: rabbitmq:3-management
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/rabbitmq
      nodeSelector:
        intended-for: ae-dev-harvest
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      storageClassName: microk8s-hostpath
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi