apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: elasticsearch
        image: us-west1-docker.pkg.dev/digital-ucdavis-edu/jm-dev/elastic-search:sandbox
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        # readinessProbe:
        #   httpGet:
        #     path: /_cluster/health?wait_for_status=yellow&timeout=30s
        #     port: 9200
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        env:
          - name: "node.name"
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "discovery.type"
            value: "multi-node"
          - name: "discovery.seed_hosts"
            value: "elasticsearch"
          - name: "cluster.initial_master_nodes"
            value: "elasticsearch-0,elasticsearch-1"
          - name: cluster.name
            value: elasticsearch
          - name: network.host
            value: 0.0.0.0
          - name: xpack.security.enabled
            value: "false"
          - name: "ES_JAVA_OPTS"
            value: "-Xms1g -Xmx1g"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: backups
          mountPath: /usr/share/elasticsearch/backups
      # - name: init-pipeline
      #   image: curlimages/curl:latest
      #   command:
      #     - /bin/sh
      #     - -c
      #     - |
      #       # Wait for Elasticsearch to be ready
      #       for i in {1..30}; do
      #         if curl -s -o /dev/null -w "%{http_code}" http://localhost:9200/ | grep -q "200"; then
      #           echo "Elasticsearch is ready"
      #           break
      #         fi
      #         echo "Waiting for Elasticsearch... attempt $i/30"
      #         sleep 2
      #       done
            
      #       # Check if pipeline exists
      #       if curl -s -o /dev/null -w "%{http_code}" http://localhost:9200/_ingest/pipeline/aggie-experts-pipeline | grep -q "200"; then
      #         echo "Pipeline already exists"
      #         exit 0
      #       else
      #         echo "Creating pipeline..."
      #         curl -X PUT -H "Content-Type: application/json" -d '{"description":"Adds a modified-date field","processors":[{"set":{"field":"modified-date","value":"{{_ingest.timestamp}}"}}]}' http://localhost:9200/_ingest/pipeline/aggie-experts-pipeline || exit 1
      #         echo "Pipeline created successfully"
      #         exit 0
      #       fi
      #   resources:
      #     requests:
      #       memory: "128Mi"
      #       cpu: "100m"
      #     limits:
      #       memory: "256Mi"
      #       cpu: "200m"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          runAsUser: 0
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: backups
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi