apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          image: us-west1-docker.pkg.dev/aggie-experts/pub/elastic-search:anduin
      nodeSelector:
        intended-for: ae-dev-frontend
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi