apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-spa
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/aggie-experts/pub/webapp:5.2.3
          env:
            - name: CLIENT_ENV
              value: prod
            - name: EXPERTS_IS_PUBLIC
              value: 'true'
      nodeSelector:
        intended-for: ae-dev-frontend
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: webapp-spa
              topologyKey: kubernetes.io/hostname
